# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBPW5IItmtnU-uOs8QRoraGBtyjER3tw
"""

import streamlit as st
st.title("hello")
st.write("thuan nguyen")
